// Mensajes que el servidor le devuelve a la persona, traducidos.
// La clave es el texto en español tal como está escrito en el código; el valor es [inglés, portugués].
// Si se agrega un mensaje nuevo en una ruta, se agrega acá también (si falta, se muestra en español).
module.exports = {
  "ID inválido": ["Invalid ID", "ID inválido"],
  "No se pudieron obtener las valoraciones": ["Could not load the reviews", "Não foi possível carregar as avaliações"],
  "No se pudo comprobar tu participación": ["Could not check your participation", "Não foi possível verificar a sua participação"],
  "Recorrido inválido": ["Invalid tour", "Roteiro inválido"],
  "La puntuación debe ser de 1 a 5 estrellas": ["The rating must be from 1 to 5 stars", "A nota deve ser de 1 a 5 estrelas"],
  "No se pudo guardar tu valoración": ["Could not save your review", "Não foi possível salvar a sua avaliação"],
  "El recorrido no existe": ["The tour does not exist", "O roteiro não existe"],
  "Vas a poder valorarlo cuando el recorrido haya finalizado.": ["You will be able to rate it once the tour has finished.", "Você poderá avaliá-lo quando o roteiro for concluído."],
  "Solo pueden valorar quienes se inscribieron y participaron del recorrido.": ["Only people who registered for and took part in the tour can rate it.", "Somente quem se inscreveu e participou do roteiro pode avaliá-lo."],
  "Usuario": ["User", "Usuário"],
  "Demasiadas búsquedas seguidas. Esperá un momento.": ["Too many searches in a row. Please wait a moment.", "Muitas pesquisas seguidas. Aguarde um momento."],
  "No se pudo realizar la búsqueda": ["The search could not be completed", "Não foi possível realizar a pesquisa"],
  "Demasiados intentos. Probá de nuevo en 15 minutos.": ["Too many attempts. Please try again in 15 minutes.", "Muitas tentativas. Tente novamente em 15 minutos."],
  "Ingresá un correo válido.": ["Enter a valid email address.", "Informe um e-mail válido."],
  "Este correo ya está suscripto. ¡Gracias!": ["This email is already subscribed. Thank you!", "Este e-mail já está inscrito. Obrigado!"],
  "¡Gracias por suscribirte! Te enviamos un correo de bienvenida.": ["Thanks for subscribing! We've sent you a welcome email.", "Obrigado por assinar! Enviamos um e-mail de boas-vindas."],
  "No pudimos completar tu suscripción. Probá de nuevo.": ["We couldn't complete your subscription. Please try again.", "Não conseguimos concluir a sua assinatura. Tente novamente."],
  "No encontrado": ["Not found", "Não encontrado"],
  "No encontrada": ["Not found", "Não encontrada"],
  "Eliminado": ["Deleted", "Excluído"],
  "Museo inválido": ["Invalid museum", "Museu inválido"],
  "Coordenadas inválidas": ["Invalid coordinates", "Coordenadas inválidas"],
  "No se pudo guardar la ubicación": ["Could not save the location", "Não foi possível salvar a localização"],
  "Enviaste muchos mensajes. Probá de nuevo en 15 minutos.": ["You've sent too many messages. Please try again in 15 minutes.", "Você enviou muitas mensagens. Tente novamente em 15 minutos."],
  "Completá tu nombre y el mensaje.": ["Please fill in your name and the message.", "Preencha o seu nome e a mensagem."],
  "El correo no es válido.": ["The email address is not valid.", "O e-mail não é válido."],
  "¡Gracias! Recibimos tu consulta y te vamos a responder pronto.": ["Thank you! We received your message and will reply soon.", "Obrigado! Recebemos a sua mensagem e responderemos em breve."],
  "No pudimos enviar tu mensaje. Probá de nuevo en unos minutos.": ["We couldn't send your message. Please try again in a few minutes.", "Não conseguimos enviar a sua mensagem. Tente novamente em alguns minutos."],
  "Actividad inválida": ["Invalid activity", "Atividade inválida"],
  "Cantidad de personas inválida": ["Invalid number of people", "Número de pessoas inválido"],
  "Completá nombre y teléfono": ["Please fill in your name and phone number", "Preencha o nome e o telefone"],
  "Ya estás inscripto en esta actividad": ["You're already registered for this activity", "Você já está inscrito nesta atividade"],
  "No hay cupos suficientes o la actividad ya finalizó": ["There aren't enough spots left or the activity has already ended", "Não há vagas suficientes ou a atividade já terminou"],
  "No se pudo completar la inscripción": ["Could not complete the registration", "Não foi possível concluir a inscrição"],
  "No se pudieron obtener tus inscripciones": ["Could not load your registrations", "Não foi possível carregar as suas inscrições"],
  "No se pudieron obtener los inscriptos": ["Could not load the registrants", "Não foi possível carregar os inscritos"],
  "No podés cancelar esta inscripción": ["You can't cancel this registration", "Você não pode cancelar esta inscrição"],
  "Inscripción cancelada": ["Registration cancelled", "Inscrição cancelada"],
  "No se pudo cancelar la inscripción": ["Could not cancel the registration", "Não foi possível cancelar a inscrição"],
  "No se pudo cargar el mapa cultural": ["Could not load the cultural map", "Não foi possível carregar o mapa cultural"],
  "Correo inválido": ["Invalid email address", "E-mail inválido"],
  "La contraseña debe tener al menos 8 caracteres": ["The password must be at least 8 characters long", "A senha deve ter pelo menos 8 caracteres"],
  "El nombre es obligatorio": ["The name is required", "O nome é obrigatório"],
  "Ya existe una cuenta con ese correo": ["An account with that email already exists", "Já existe uma conta com esse e-mail"],
  "Cuenta creada. Te enviamos un correo para confirmarla.": ["Account created. We've sent you an email to confirm it.", "Conta criada. Enviamos um e-mail para confirmá-la."],
  "No se pudo registrar el usuario": ["Could not register the user", "Não foi possível cadastrar o usuário"],
  "Los datos ingresados son incorrectos": ["The details you entered are incorrect", "Os dados informados estão incorretos"],
  "No se pudo iniciar sesión": ["Could not log in", "Não foi possível entrar"],
  "El nombre no puede estar vacío": ["The name cannot be empty", "O nome não pode ficar vazio"],
  "Teléfono inválido": ["Invalid phone number", "Telefone inválido"],
  "La foto no es válida o pesa demasiado": ["The photo is not valid or is too large", "A foto não é válida ou é muito grande"],
  "No se pudo actualizar el perfil": ["Could not update the profile", "Não foi possível atualizar o perfil"],
  "La nueva contraseña debe tener al menos 8 caracteres": ["The new password must be at least 8 characters long", "A nova senha deve ter pelo menos 8 caracteres"],
  "La contraseña actual es incorrecta": ["The current password is incorrect", "A senha atual está incorreta"],
  "Contraseña actualizada": ["Password updated", "Senha atualizada"],
  "No se pudo cambiar la contraseña": ["Could not change the password", "Não foi possível alterar a senha"],
  "Si el correo está registrado, te enviamos un enlace para restablecer tu contraseña. Revisá también la carpeta de spam.": ["If the email is registered, we've sent you a link to reset your password. Check your spam folder too.", "Se o e-mail estiver cadastrado, enviamos um link para redefinir a sua senha. Verifique também a pasta de spam."],
  "El enlace no es válido o ya venció. Pedí uno nuevo.": ["The link is not valid or has expired. Request a new one.", "O link não é válido ou já expirou. Peça um novo."],
  "No se pudo restablecer la contraseña": ["Could not reset the password", "Não foi possível redefinir a senha"],
  "Contraseña actualizada. Ya podés iniciar sesión.": ["Password updated. You can now log in.", "Senha atualizada. Agora você já pode entrar."],
  "Sesión cerrada": ["Logged out", "Sessão encerrada"],
  "El enlace no es válido o ya venció. Pedí uno nuevo desde tu cuenta.": ["The link is not valid or has expired. Request a new one from your account.", "O link não é válido ou já expirou. Peça um novo na sua conta."],
  "¡Listo! Tu correo quedó confirmado.": ["Done! Your email has been confirmed.", "Pronto! O seu e-mail foi confirmado."],
  "No se pudo verificar el correo": ["Could not verify the email", "Não foi possível verificar o e-mail"],
  "Tu correo ya está confirmado.": ["Your email is already confirmed.", "O seu e-mail já está confirmado."],
  "Te enviamos un correo nuevo. Revisá también la carpeta de spam.": ["We've sent you a new email. Check your spam folder too.", "Enviamos um novo e-mail. Verifique também a pasta de spam."],
  "No se pudo enviar el correo. Probá de nuevo en unos minutos.": ["Could not send the email. Please try again in a few minutes.", "Não foi possível enviar o e-mail. Tente novamente em alguns minutos."],
  "Hiciste muchas consultas seguidas. Probá de nuevo en unos minutos.": ["You've asked too many questions in a row. Please try again in a few minutes.", "Você fez muitas consultas seguidas. Tente novamente em alguns minutos."],
  "El asistente no está disponible por ahora.": ["The assistant is not available right now.", "O assistente não está disponível no momento."],
  "Escribí un mensaje para el asistente.": ["Write a message for the assistant.", "Escreva uma mensagem para o assistente."],
  "No pude conectarme con el asistente. Probá de nuevo en un momento.": ["I couldn't connect to the assistant. Please try again in a moment.", "Não consegui me conectar com o assistente. Tente novamente em instantes."],
  "Perdón, no pude generar una respuesta. Probá de nuevo.": ["Sorry, I couldn't come up with an answer. Please try again.", "Desculpe, não consegui gerar uma resposta. Tente novamente."],
  "Necesitás iniciar sesión": ["You need to log in", "Você precisa entrar na sua conta"],
  "Pedido no permitido": ["Request not allowed", "Pedido não permitido"],
  "Sesión inválida": ["Invalid session", "Sessão inválida"],
  "Sesión inválida o vencida": ["Invalid or expired session", "Sessão inválida ou expirada"],
  "No tenés permisos de administrador": ["You don't have administrator permissions", "Você não tem permissões de administrador"],
  "Confirmá tu correo para continuar. Te enviamos un enlace cuando te registraste.": ["Confirm your email to continue. We sent you a link when you signed up.", "Confirme o seu e-mail para continuar. Enviamos um link quando você se cadastrou."],
  "No se pudo conectar a la base de datos": ["Could not connect to the database", "Não foi possível conectar ao banco de dados"],
  "El servidor funciona": ["The server is running", "O servidor está funcionando"],
  "Colonia del Sacramento": ["Colonia del Sacramento", "Colônia do Sacramento"],
};
